_wandb:
    value:
        cli_version: 0.18.1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 71
                - 103
            "2":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 71
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.12.4
            "5": 0.18.1
            "6": 4.45.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
